[workspace]
members = [
  "http-api",
  "git-server",
  "service-init",
  "shared",
]

[patch.crates-io.librad]
git = "https://github.com/radicle-dev/radicle-link"
rev = "a9485b78b5c78d252c92f61d990cf34622d1c8f1"

[patch.crates-io.lnk-clib]
git = "https://github.com/radicle-dev/radicle-link"
rev = "a9485b78b5c78d252c92f61d990cf34622d1c8f1"

[patch.crates-io.lnk-identities]
git = "https://github.com/radicle-dev/radicle-link"
rev = "a9485b78b5c78d252c92f61d990cf34622d1c8f1"

[patch.crates-io.radicle-git-ext]
git = "https://github.com/radicle-dev/radicle-link"
rev = "a9485b78b5c78d252c92f61d990cf34622d1c8f1"

[patch.crates-io.lnk-profile]
git = "https://github.com/radicle-dev/radicle-link"
rev = "a9485b78b5c78d252c92f61d990cf34622d1c8f1"

[patch.crates-io.git-trailers]
git = "https://github.com/radicle-dev/radicle-link"
rev = "a9485b78b5c78d252c92f61d990cf34622d1c8f1"

[patch.crates-io.git-ref-format]
git = "https://github.com/radicle-dev/radicle-link"
rev = "a9485b78b5c78d252c92f61d990cf34622d1c8f1"

[patch.crates-io.radicle-common]
git = "https://github.com/radicle-dev/radicle-cli"
rev = "9052c294e4c6d1d19d665ef058eaf7ba1a2c9718"

[patch.crates-io.automerge]
git = "https://github.com/automerge/automerge-rs"
rev = "291557a019acac283e54ea31a9fad81ed65736ab"

[profile.release]
debug = true
